#!/bin/bash

[[ $(id -u) -eq 0 ]] || {
        echo " [x] You must be root to run this script. Exit"
        exit 1
}

echo " [+] TorSystem installer"

echo " [+] [+] Installing prerequisites "
apt-get update 1>/dev/null 2>&1
apt-get install tor -y 1>/dev/null 2>&1

echo " [+] [+] Creating /opt/torsystem configuration folder "
mkdir -p /opt/torsystem
rm -rf /opt/torsystem/*
cp -r conf /opt/torsystem
cp /etc/resolv.conf /opt/torsystem/conf/default_resolv.conf

cp -p torsystem.sh /usr/bin/torsystem
if [ $? -eq 0 ]; then
    echo " [+] [+] [SUCCESS] Copied binary to /usr/bin"
else
    echo " [x] [ERROR] Unable to copy"
    exit 1
fi

echo " [+] Installation completed"
echo "

████████╗ ██████╗ ██████╗ ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗
╚══██╔══╝██╔═══██╗██╔══██╗██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║
   ██║   ██║   ██║██████╔╝███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║
   ██║   ██║   ██║██╔══██╗╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║
   ██║   ╚██████╔╝██║  ██║███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║
   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝


github.com/marcodebona1994/torsystem


"
echo  "TorSystem usage:
    -s, --start            # Start TorSystem
    -n, --new-circuit      # Request new tor exit node
    -x, --stop             # Stop TorSystem
    -b  --backup           # Create backup for restoring networking system
    -h  --help"
